import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "FAQ — GenChords",
  description: "Frequently asked questions about GenChords — AI chord progression generator for music producers.",
};

const FAQS = [
  {
    q: "What is GenChords?",
    a: "GenChords is an AI-powered tool that generates chord progressions based on your creative direction. You describe a mood or style, set parameters like key, scale, and genre, and the AI creates harmonically rich progressions you can export as MIDI."
  },
  {
    q: "How does the AI generate chords?",
    a: "We use Google's Gemini AI model with carefully engineered prompts that encode music theory rules — proper voice leading, genre conventions, tension and resolution patterns, and more. The AI outputs structured chord data that we validate before presenting it to you."
  },
  {
    q: "What format are the exports?",
    a: "Progressions are exported as standard MIDI files (.mid). These can be imported into any DAW — Ableton Live, FL Studio, Logic Pro, Pro Tools, Cubase, Studio One, and more. Just drag and drop the file onto a MIDI track."
  },
  {
    q: "Is it free to use?",
    a: "Yes. The free tier gives you 10 generations per day with 1 variation per generation. All keys, scales, genres, MIDI export, and in-browser playback are included. Pro plans with unlimited generations and more variations are coming soon."
  },
  {
    q: "Can I use the generated chords in commercial music?",
    a: "Yes. All chord progressions generated by GenChords are yours to use in any project — commercial or personal. Chord progressions themselves are not copyrightable."
  },
  {
    q: "What keys and scales are supported?",
    a: "All 12 keys (C through B, including sharps and flats) and 12 scales: major, minor, dorian, mixolydian, phrygian, lydian, locrian, harmonic minor, melodic minor, pentatonic major, pentatonic minor, and blues."
  },
  {
    q: "Can I let the AI choose the key and scale?",
    a: "Yes. There's an 'AI decides' option for both key and scale. The AI will choose what best fits your prompt and genre."
  },
  {
    q: "How many variations can I generate at once?",
    a: "Free users get 1 variation per generation. Pro users can generate up to 4 variations at once to compare different options side by side."
  },
  {
    q: "Do I need an account?",
    a: "No account is needed to generate and export progressions. Sign in if you want to save progressions to your dashboard for later access."
  },
  {
    q: "What DAWs are compatible?",
    a: "Any DAW that supports standard MIDI files — which is essentially all of them. This includes Ableton Live, FL Studio, Logic Pro, Pro Tools, Cubase, Studio One, Reaper, Bitwig, GarageBand, and more."
  },
];

export default function FAQPage() {
  return (
    <div className="page-shell max-w-3xl py-16 sm:py-20">
      <div className="mb-12">
        <p className="section-label mb-3">FAQ</p>
        <h1 className="mb-3 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Frequently Asked Questions</h1>
        <p className="text-[var(--text-soft)]">
          Everything you need to know about GenChords.
        </p>
      </div>

      <div className="surface-card overflow-hidden">
        {FAQS.map((faq, i) => (
          <div key={i} className={`p-6 ${i > 0 ? "border-t border-[var(--border)]" : ""}`}>
            <h3 className="mb-2 text-lg font-medium">{faq.q}</h3>
            <p className="text-sm leading-relaxed text-[var(--text-muted)]">{faq.a}</p>
          </div>
        ))}
      </div>

      <div className="mt-16 text-center">
        <p className="mb-4 text-[var(--text-soft)]">Still have questions?</p>
        <div className="flex items-center justify-center gap-3">
          <Link href="/generate" className="button-primary inline-flex h-10 items-center justify-center px-6 text-sm font-medium">
            Try it out
          </Link>
          <Link href="/blog" className="button-secondary inline-flex h-10 items-center justify-center px-6 text-sm font-medium">
            Read the blog
          </Link>
        </div>
      </div>
    </div>
  );
}
